import type {
  ActivityRecord,
  AssetRecord,
  DocumentRecord,
  EmployeeRecord,
  KpiRecord,
  Project,
  QualityRecord,
  SafetyRecord,
  SupplierRecord,
  WorkItem,
  WorkState,
} from "./types";

const projectCodes = [
  "CIWS-26",
  "S010042",
  "S010067",
  "S010068",
  "S010088",
  "S010097",
  "50544",
] as const;

const pad = (value: number, width = 3) => String(value).padStart(width, "0");

const dateFromOffset = (offset: number) => {
  const date = new Date(Date.UTC(2026, 6, 18 + offset));
  return date.toISOString().slice(0, 10);
};

export const projects: Project[] = [
  {
    id: "CIWS-26",
    name: "CIWS firing unit integration",
    customer: "Indian Navy",
    owner: "Farhan Patil",
    stage: "Prototype integration",
    completion: 62,
    risk: "High",
    riskDriver: "Upper gun stand import clearance",
    trend: "Worsening",
    nextMilestone: "Integrated shop trial",
    due: "2026-08-14",
    openActions: 8,
  },
  {
    id: "S010042",
    name: "Urea stripper completion",
    customer: "CFCL",
    owner: "Chetan Kulkarni",
    stage: "Final fabrication",
    completion: 84,
    risk: "Medium",
    riskDriver: "DP28W welding consumable balance",
    trend: "Improving",
    nextMilestone: "Final hydrotest",
    due: "2026-07-29",
    openActions: 4,
  },
  {
    id: "S010067",
    name: "Texas tower train A",
    customer: "Bechtel",
    owner: "Gauri Kulkarni",
    stage: "Tube replacement",
    completion: 71,
    risk: "High",
    riskDriver: "Replacement tube delivery",
    trend: "Flat",
    nextMilestone: "ECT clearance",
    due: "2026-08-08",
    openActions: 7,
  },
  {
    id: "S010068",
    name: "Texas tower train B",
    customer: "Bechtel",
    owner: "Harish Kulkarni",
    stage: "NDT and closure",
    completion: 78,
    risk: "Medium",
    riskDriver: "Borescopy agency availability",
    trend: "Improving",
    nextMilestone: "Customer hold point release",
    due: "2026-08-12",
    openActions: 5,
  },
  {
    id: "S010088",
    name: "Secondary reformer transfer line",
    customer: "Zuari Agro Chemicals",
    owner: "Isha Kulkarni",
    stage: "Section assembly",
    completion: 56,
    risk: "High",
    riskDriver: "Refractory inspection sequence",
    trend: "Worsening",
    nextMilestone: "Section 4 fit-up",
    due: "2026-08-21",
    openActions: 11,
  },
  {
    id: "S010097",
    name: "Shutdown spares lot 1",
    customer: "SABIC-SAFCO",
    owner: "Jatin Kulkarni",
    stage: "Final inspection",
    completion: 91,
    risk: "Low",
    riskDriver: "Export packing sign-off",
    trend: "Improving",
    nextMilestone: "Dispatch release note",
    due: "2026-07-24",
    openActions: 2,
  },
  {
    id: "50544",
    name: "RAPP feedwater heater package",
    customer: "NPCIL",
    owner: "Kavita Kulkarni",
    stage: "Tube bundle assembly",
    completion: 68,
    risk: "Medium",
    riskDriver: "Full kit readiness for LP heater",
    trend: "Flat",
    nextMilestone: "LP2 bundle insertion",
    due: "2026-08-18",
    openActions: 6,
  },
  {
    id: "S010084",
    name: "Primary compressor cooler",
    customer: "Reliance Industries",
    owner: "Meera Kulkarni",
    stage: "Customer documentation",
    completion: 95,
    risk: "Low",
    riskDriver: "Final MDR index approval",
    trend: "Improving",
    nextMilestone: "Manufacturing record book release",
    due: "2026-07-23",
    openActions: 1,
  },
  {
    id: "ARDE-120",
    name: "120 mm ammunition handling system",
    customer: "ARDE",
    owner: "Nikhil Kulkarni",
    stage: "Supply chain development",
    completion: 34,
    risk: "Medium",
    riskDriver: "Explosive partner qualification",
    trend: "Flat",
    nextMilestone: "Partner technical audit",
    due: "2026-09-11",
    openActions: 5,
  },
  {
    id: "L70-SUC",
    name: "L70 successor concept",
    customer: "Indian Army",
    owner: "Pooja Kulkarni",
    stage: "Concept definition",
    completion: 22,
    risk: "Low",
    riskDriver: "Customer requirement baseline",
    trend: "Improving",
    nextMilestone: "Concept review",
    due: "2026-09-25",
    openActions: 3,
  },
];

export const workItems: WorkItem[] = [
  {
    id: "WK-001",
    title: "Release CIWS upper gun stand fit-up",
    type: "Project",
    priority: "Critical",
    state: "Blocked",
    owner: "Rohit Kulkarni",
    ownerRole: "Project Engineer",
    supervisor: "Farhan Patil",
    station: "Integration Bay 2",
    unit: "Unit 2",
    shift: "Day",
    due: "2026-07-18T10:30:00+05:30",
    overdueMinutes: 645,
    project: "CIWS-26",
    evidenceCount: 2,
    blocker: "Import clearance copy is not attached",
    checklistDone: 4,
    checklistTotal: 7,
    updatedAt: "2026-07-18T17:42:00+05:30",
  },
  {
    id: "WK-002",
    title: "Complete Urea stripper root pass inspection",
    type: "Quality",
    priority: "High",
    state: "Awaiting verification",
    owner: "Deepak Kulkarni",
    ownerRole: "QC Inspector",
    supervisor: "Deepak Patil",
    station: "Welding Bay 4",
    unit: "Unit 2",
    shift: "Day",
    due: "2026-07-18T14:00:00+05:30",
    overdueMinutes: 435,
    project: "S010042",
    evidenceCount: 5,
    checklistDone: 6,
    checklistTotal: 6,
    updatedAt: "2026-07-18T15:11:00+05:30",
  },
  {
    id: "WK-003",
    title: "Machine replacement tube sheet pocket",
    type: "Production",
    priority: "Critical",
    state: "In progress",
    owner: "Arjun Kulkarni",
    ownerRole: "CNC Operator",
    supervisor: "Arjun Patil",
    station: "HB-04",
    unit: "Unit 1",
    shift: "Night",
    due: "2026-07-19T06:00:00+05:30",
    project: "S010067",
    asset: "Horizontal Borer HB-04",
    evidenceCount: 1,
    checklistDone: 3,
    checklistTotal: 8,
    updatedAt: "2026-07-18T20:08:00+05:30",
  },
  {
    id: "WK-004",
    title: "Approve ECT agency mobilization plan",
    type: "Project",
    priority: "High",
    state: "Not started",
    owner: "Gauri Kulkarni",
    ownerRole: "Project Engineer",
    supervisor: "Farhan Patil",
    station: "Project Office",
    unit: "Unit 2",
    shift: "Day",
    due: "2026-07-19T12:00:00+05:30",
    project: "S010067",
    evidenceCount: 0,
    checklistDone: 0,
    checklistTotal: 4,
    updatedAt: "2026-07-18T16:10:00+05:30",
  },
  {
    id: "WK-005",
    title: "Repair SAW-03 wire feed fault",
    type: "Maintenance",
    priority: "Critical",
    state: "Blocked",
    owner: "Divya Kulkarni",
    ownerRole: "Maintenance Technician",
    supervisor: "Divya Patil",
    station: "Welding Bay 3",
    unit: "Unit 2",
    shift: "Night",
    due: "2026-07-18T18:00:00+05:30",
    overdueMinutes: 195,
    asset: "SAW Station SAW-03",
    evidenceCount: 1,
    blocker: "Drive card replacement is awaiting stores issue",
    checklistDone: 2,
    checklistTotal: 5,
    updatedAt: "2026-07-18T20:22:00+05:30",
  },
  {
    id: "WK-006",
    title: "Verify refractory inspection hold point",
    type: "Quality",
    priority: "High",
    state: "In progress",
    owner: "Chetan Deshmukh",
    ownerRole: "Quality Engineer",
    supervisor: "Chetan Patil",
    station: "Assembly Bay 6",
    unit: "Unit 2",
    shift: "Day",
    due: "2026-07-19T16:00:00+05:30",
    project: "S010088",
    evidenceCount: 3,
    checklistDone: 5,
    checklistTotal: 9,
    updatedAt: "2026-07-18T18:55:00+05:30",
  },
  {
    id: "WK-007",
    title: "Close export packing punch points",
    type: "Production",
    priority: "High",
    state: "Awaiting verification",
    owner: "Aditi Deshmukh",
    ownerRole: "Production Operator",
    supervisor: "Aditi Patil",
    station: "Dispatch Bay",
    unit: "Unit 2",
    shift: "Day",
    due: "2026-07-18T19:00:00+05:30",
    overdueMinutes: 135,
    project: "S010097",
    evidenceCount: 7,
    checklistDone: 8,
    checklistTotal: 8,
    updatedAt: "2026-07-18T19:18:00+05:30",
  },
  {
    id: "WK-008",
    title: "Calibrate UT set before LP2 scan",
    type: "Quality",
    priority: "Critical",
    state: "Not started",
    owner: "Harish Deshmukh",
    ownerRole: "NDT Technician",
    supervisor: "Deepak Patil",
    station: "NDT Room",
    unit: "Unit 1",
    shift: "Day",
    due: "2026-07-19T08:30:00+05:30",
    project: "50544",
    asset: "UT Set UT-07",
    evidenceCount: 0,
    checklistDone: 0,
    checklistTotal: 6,
    updatedAt: "2026-07-18T17:05:00+05:30",
  },
  {
    id: "WK-009",
    title: "Issue confined space permit for tube side entry",
    type: "Safety",
    priority: "Critical",
    state: "In progress",
    owner: "Kavita Deshmukh",
    ownerRole: "Safety Officer",
    supervisor: "Kavita Patil",
    station: "Assembly Bay 2",
    unit: "Unit 1",
    shift: "Night",
    due: "2026-07-18T22:00:00+05:30",
    project: "50544",
    evidenceCount: 2,
    checklistDone: 7,
    checklistTotal: 10,
    updatedAt: "2026-07-18T20:31:00+05:30",
  },
  {
    id: "WK-010",
    title: "Acknowledge revised WPS-17",
    type: "Document",
    priority: "Medium",
    state: "In progress",
    owner: "Bhavna Deshmukh",
    ownerRole: "Welder",
    supervisor: "Bhavna Patil",
    station: "Welding Bay 1",
    unit: "Unit 1",
    shift: "Day",
    due: "2026-07-20T12:00:00+05:30",
    evidenceCount: 0,
    checklistDone: 1,
    checklistTotal: 2,
    updatedAt: "2026-07-18T12:44:00+05:30",
  },
  {
    id: "WK-011",
    title: "Complete daily action list review",
    type: "Project",
    priority: "High",
    state: "Closed",
    owner: "Farhan Deshmukh",
    ownerRole: "Project Engineer",
    supervisor: "Farhan Patil",
    station: "Project Office",
    unit: "Unit 2",
    shift: "Day",
    due: "2026-07-18T09:30:00+05:30",
    project: "CIWS-26",
    evidenceCount: 4,
    checklistDone: 5,
    checklistTotal: 5,
    updatedAt: "2026-07-18T09:22:00+05:30",
  },
  {
    id: "WK-012",
    title: "Inspect crane hook before heavy lift",
    type: "Safety",
    priority: "High",
    state: "Awaiting verification",
    owner: "Suresh Deshmukh",
    ownerRole: "Safety Technician",
    supervisor: "Kavita Patil",
    station: "Heavy Fabrication Bay",
    unit: "Unit 2",
    shift: "Night",
    due: "2026-07-18T20:00:00+05:30",
    overdueMinutes: 75,
    asset: "EOT Crane CR-12",
    evidenceCount: 3,
    checklistDone: 5,
    checklistTotal: 5,
    updatedAt: "2026-07-18T20:06:00+05:30",
  },
  {
    id: "WK-013",
    title: "Finish LP2 bundle dimensional report",
    type: "Quality",
    priority: "High",
    state: "In progress",
    owner: "Deepak Deshmukh",
    ownerRole: "QC Inspector",
    supervisor: "Deepak Patil",
    station: "Metrology Lab",
    unit: "Unit 1",
    shift: "Day",
    due: "2026-07-20T15:00:00+05:30",
    project: "50544",
    asset: "CMM CMM-02",
    evidenceCount: 6,
    checklistDone: 6,
    checklistTotal: 11,
    updatedAt: "2026-07-18T18:36:00+05:30",
  },
  {
    id: "WK-014",
    title: "Confirm material full kit for section 4",
    type: "Project",
    priority: "Critical",
    state: "Blocked",
    owner: "Gauri Deshmukh",
    ownerRole: "Buyer",
    supervisor: "Gauri Patil",
    station: "Project Stores",
    unit: "Unit 2",
    shift: "Day",
    due: "2026-07-18T16:00:00+05:30",
    overdueMinutes: 315,
    project: "S010088",
    evidenceCount: 2,
    blocker: "Two refractory anchors are short against the BOM",
    checklistDone: 18,
    checklistTotal: 20,
    updatedAt: "2026-07-18T19:47:00+05:30",
  },
  {
    id: "WK-015",
    title: "Perform compressor PM checklist",
    type: "Maintenance",
    priority: "Medium",
    state: "In progress",
    owner: "Divya Deshmukh",
    ownerRole: "Maintenance Technician",
    supervisor: "Divya Patil",
    station: "Utility Block",
    unit: "Unit 1",
    shift: "Day",
    due: "2026-07-20T11:00:00+05:30",
    asset: "Air Compressor AC-02",
    evidenceCount: 1,
    checklistDone: 4,
    checklistTotal: 12,
    updatedAt: "2026-07-18T16:28:00+05:30",
  },
  {
    id: "WK-016",
    title: "Approve manufacturing record book index",
    type: "Document",
    priority: "Medium",
    state: "Awaiting verification",
    owner: "Chetan Patil",
    ownerRole: "Quality Supervisor",
    supervisor: "Ganesh Badgujar",
    station: "QA Office",
    unit: "Unit 1",
    shift: "Day",
    due: "2026-07-19T17:30:00+05:30",
    project: "S010084",
    evidenceCount: 12,
    checklistDone: 9,
    checklistTotal: 9,
    updatedAt: "2026-07-18T18:01:00+05:30",
  },
  {
    id: "WK-017",
    title: "Conduct night shift toolbox talk",
    type: "Safety",
    priority: "Medium",
    state: "Not started",
    owner: "Kavita Patil",
    ownerRole: "Safety Supervisor",
    supervisor: "Ganesh Badgujar",
    station: "Unit 2 Muster Point",
    unit: "Unit 2",
    shift: "Night",
    due: "2026-07-18T21:45:00+05:30",
    evidenceCount: 0,
    checklistDone: 0,
    checklistTotal: 3,
    updatedAt: "2026-07-18T18:12:00+05:30",
  },
  {
    id: "WK-018",
    title: "Close customer punch point 17",
    type: "Quality",
    priority: "High",
    state: "Closed",
    owner: "Deepak Patil",
    ownerRole: "QC Supervisor",
    supervisor: "Ganesh Badgujar",
    station: "Final Inspection Bay",
    unit: "Unit 2",
    shift: "Day",
    due: "2026-07-18T13:00:00+05:30",
    project: "S010097",
    evidenceCount: 8,
    checklistDone: 7,
    checklistTotal: 7,
    updatedAt: "2026-07-18T12:51:00+05:30",
  },
  {
    id: "WK-019",
    title: "Replace VTL-02 spindle temperature sensor",
    type: "Maintenance",
    priority: "High",
    state: "Not started",
    owner: "Uday Deshmukh",
    ownerRole: "Electrical Technician",
    supervisor: "Divya Patil",
    station: "Machine Shop",
    unit: "Unit 1",
    shift: "Night",
    due: "2026-07-19T04:00:00+05:30",
    asset: "Vertical Turning Lathe VTL-02",
    evidenceCount: 0,
    checklistDone: 0,
    checklistTotal: 5,
    updatedAt: "2026-07-18T20:14:00+05:30",
  },
  {
    id: "WK-020",
    title: "Submit rolled thread deviation response",
    type: "Document",
    priority: "High",
    state: "In progress",
    owner: "Jatin Deshmukh",
    ownerRole: "Project Coordinator",
    supervisor: "Farhan Patil",
    station: "Project Office",
    unit: "Unit 2",
    shift: "Day",
    due: "2026-07-21T12:00:00+05:30",
    project: "S010084",
    evidenceCount: 3,
    checklistDone: 2,
    checklistTotal: 4,
    updatedAt: "2026-07-18T17:26:00+05:30",
  },
];

const firstNames = [
  "Aditi",
  "Arjun",
  "Bhavna",
  "Chetan",
  "Deepak",
  "Divya",
  "Farhan",
  "Gauri",
  "Harish",
  "Isha",
  "Jatin",
  "Kavita",
  "Kiran",
  "Meera",
  "Nikhil",
  "Pooja",
  "Prakash",
  "Rahul",
  "Rina",
  "Rohit",
  "Sameer",
  "Sneha",
  "Suresh",
  "Tanvi",
  "Uday",
  "Varsha",
  "Vijay",
  "Yash",
  "Zoya",
] as const;

const lastNames = ["Patil", "Kulkarni", "Deshmukh"] as const;

const departmentDefinitions = [
  { department: "Production", supervisor: "Aditi Patil", role: "Production Operator" },
  { department: "Machine Shop", supervisor: "Arjun Patil", role: "CNC Operator" },
  { department: "Welding Engineering", supervisor: "Bhavna Patil", role: "Welder" },
  { department: "Quality Assurance", supervisor: "Chetan Patil", role: "Quality Engineer" },
  { department: "Quality Control", supervisor: "Deepak Patil", role: "QC Inspector" },
  { department: "Maintenance", supervisor: "Divya Patil", role: "Maintenance Technician" },
  { department: "Project Management", supervisor: "Farhan Patil", role: "Project Engineer" },
  { department: "SCM", supervisor: "Gauri Patil", role: "Buyer" },
  { department: "Finance & Accounts", supervisor: "Harish Patil", role: "Finance Analyst" },
  { department: "HR & Administration", supervisor: "Isha Patil", role: "HR Executive" },
  { department: "Business Development", supervisor: "Jatin Patil", role: "Sales Engineer" },
  { department: "Safety", supervisor: "Kavita Patil", role: "Safety Officer" },
] as const;

const absentEmployees = new Set([12, 37, 64, 81]);
const leaveEmployees = new Set([18, 45, 72]);
const trainingEmployees = new Set([9, 30, 51, 78]);

export const employees: EmployeeRecord[] = Array.from(
  { length: 83 },
  (_, index): EmployeeRecord => {
    const employeeNumber = index + 1;
    const definition = departmentDefinitions[index % departmentDefinitions.length];
    const name = `${firstNames[index % firstNames.length]} ${
      lastNames[Math.floor(index / firstNames.length)]
    }`;
    let status: EmployeeRecord["status"] = "Present";

    if (absentEmployees.has(employeeNumber)) status = "Absent";
    if (leaveEmployees.has(employeeNumber)) status = "On leave";
    if (trainingEmployees.has(employeeNumber)) status = "Training";

    return {
      id: `EMP-${pad(employeeNumber)}`,
      name,
      role:
        index < departmentDefinitions.length
          ? `${definition.department} Supervisor`
          : definition.role,
      department: definition.department,
      unit: index < 27 ? "Unit 1" : "Unit 2",
      supervisor:
        index < departmentDefinitions.length ? "Ganesh Badgujar" : definition.supervisor,
      shift: index % 4 === 0 || index % 4 === 3 ? "Night" : "Day",
      status,
      skillCoverage: 68 + ((index * 7) % 33),
      assignedWork: (index * 3) % 6,
    };
  },
);

export const projectEmployeeAssignments: Record<(typeof projectCodes)[number], string[]> = {
  "CIWS-26": ["EMP-004", "EMP-007", "EMP-010", "EMP-013", "EMP-028", "EMP-031"],
  S010042: ["EMP-016", "EMP-019", "EMP-022", "EMP-034", "EMP-037"],
  S010067: ["EMP-025", "EMP-029", "EMP-040", "EMP-043"],
  S010068: ["EMP-032", "EMP-035", "EMP-046", "EMP-049"],
  S010088: ["EMP-038", "EMP-041", "EMP-052", "EMP-055"],
  S010097: ["EMP-044", "EMP-047", "EMP-058", "EMP-061"],
  "50544": ["EMP-050", "EMP-053", "EMP-064", "EMP-067"],
};

const findingTitles = [
  "Material traceability gap",
  "Weld parameter outside WPS range",
  "Inspection stamp not legible",
  "Calibration label expired",
  "Heat number transfer incomplete",
  "Traveler sign-off missing",
  "NDT report revision mismatch",
  "Incoming material damage",
  "Dimensional result outside tolerance",
  "Document revision used at station",
  "Supplier certificate incomplete",
  "Hold point bypass evidence missing",
] as const;

const findingAreas = [
  "Machine Shop",
  "Welding Bay 1",
  "Welding Bay 4",
  "Incoming Inspection",
  "Final Inspection",
  "Assembly Bay 2",
  "Assembly Bay 6",
  "Project Stores",
] as const;

const findingSources = [
  "AS9100 internal audit",
  "DGQA surveillance",
  "Process audit",
  "Incoming inspection audit",
  "Final inspection audit",
  "Supplier quality audit",
  "5S layered audit",
] as const;

const qualityOwners = [
  "Chetan Patil",
  "Deepak Patil",
  "Chetan Kulkarni",
  "Deepak Kulkarni",
  "Harish Deshmukh",
] as const;

const findingState = (index: number): WorkState => {
  if (index % 13 === 0) return "Blocked";
  if (index % 7 === 0) return "Awaiting verification";
  if (index % 11 === 0) return "Closed";
  return "In progress";
};

const auditFindings: QualityRecord[] = Array.from({ length: 83 }, (_, index) => {
  const kind: QualityRecord["kind"] =
    index < 22 ? "Major NC" : index < 56 ? "Minor NC" : "Observation";
  const area = findingAreas[index % findingAreas.length];

  return {
    id: `${kind === "Major NC" ? "MNC" : kind === "Minor NC" ? "NC" : "OBS"}-${pad(
      index + 1,
    )}`,
    title: `${findingTitles[index % findingTitles.length]} - ${area}`,
    kind,
    source: findingSources[index % findingSources.length],
    owner: qualityOwners[index % qualityOwners.length],
    due: dateFromOffset((index % 42) - 12),
    state: findingState(index),
    ageDays: 2 + ((index * 5) % 61),
    project: index % 4 === 0 ? undefined : projectCodes[index % projectCodes.length],
  };
});

const correctiveActions: QualityRecord[] = Array.from(
  { length: 6 },
  (_, index): QualityRecord => ({
    id: `CAPA-${pad(index + 1)}`,
    title: [
      "Standardize heat number transfer checkpoints",
      "Retrain welders on WPS parameter recording",
      "Introduce pre-use gauge verification",
      "Correct document distribution at workstations",
      "Qualify backup ECT inspection agency",
      "Add supplier certificate completeness gate",
    ][index],
    kind: "CAPA",
    source: `Major NC MNC-${pad(index + 1)}`,
    owner: qualityOwners[index % qualityOwners.length],
    due: dateFromOffset(5 + index * 4),
    state:
      index === 1 ? "Blocked" : index === 4 ? "Awaiting verification" : "In progress",
    ageDays: 8 + index * 6,
    project: projectCodes[index],
  }),
);

const qualityHolds: QualityRecord[] = Array.from(
  { length: 4 },
  (_, index): QualityRecord => ({
    id: `HOLD-${pad(index + 1)}`,
    title: [
      "Hold LP2 tube bundle for traceability review",
      "Hold Urea stripper seam for RT disposition",
      "Hold Texas tower tubes pending ECT clearance",
      "Hold CIWS base frame pending dimensional verification",
    ][index],
    kind: "Hold",
    source: "Final inspection",
    owner: qualityOwners[(index + 1) % qualityOwners.length],
    due: dateFromOffset(index + 1),
    state: index === 2 ? "Awaiting verification" : "Blocked",
    ageDays: 1 + index * 3,
    project: ["50544", "S010042", "S010067", "CIWS-26"][index],
  }),
);

export const qualityRecords: QualityRecord[] = [
  ...auditFindings,
  ...correctiveActions,
  ...qualityHolds,
];

export const assets: AssetRecord[] = [
  { id: "AST-001", name: "Horizontal Borer HB-04", area: "Machine Shop", health: "Attention", owner: "Arjun Patil", nextService: "2026-07-22", openWork: 2, runtimeHours: 18432 },
  { id: "AST-002", name: "Vertical Turning Lathe VTL-02", area: "Machine Shop", health: "Attention", owner: "Arjun Patil", nextService: "2026-07-19", openWork: 1, runtimeHours: 22109 },
  { id: "AST-003", name: "CNC Mill MCV-06", area: "Machine Shop", health: "Available", owner: "Arjun Kulkarni", nextService: "2026-08-06", openWork: 0, runtimeHours: 9632 },
  { id: "AST-004", name: "SAW Station SAW-03", area: "Welding Bay 3", health: "Down", owner: "Bhavna Patil", nextService: "2026-07-18", openWork: 3, runtimeHours: 12886 },
  { id: "AST-005", name: "GTAW Station GTAW-08", area: "Welding Bay 1", health: "Available", owner: "Bhavna Kulkarni", nextService: "2026-08-02", openWork: 0, runtimeHours: 7240 },
  { id: "AST-006", name: "RT Enclosure RT-01", area: "NDT", health: "Available", owner: "Deepak Patil", nextService: "2026-08-15", openWork: 0, runtimeHours: 5811 },
  { id: "AST-007", name: "UT Set UT-07", area: "NDT", health: "Calibration hold", owner: "Harish Deshmukh", nextService: "2026-07-19", openWork: 1, runtimeHours: 3244 },
  { id: "AST-008", name: "CMM CMM-02", area: "Metrology Lab", health: "Available", owner: "Chetan Patil", nextService: "2026-08-11", openWork: 0, runtimeHours: 4108 },
  { id: "AST-009", name: "Air Compressor AC-02", area: "Utility Block", health: "Attention", owner: "Divya Patil", nextService: "2026-07-20", openWork: 2, runtimeHours: 30214 },
  { id: "AST-010", name: "EOT Crane CR-12", area: "Heavy Fabrication Bay", health: "Available", owner: "Divya Kulkarni", nextService: "2026-07-28", openWork: 1, runtimeHours: 15890 },
  { id: "AST-011", name: "Hydrotest Pump HP-05", area: "Test Bay", health: "Available", owner: "Divya Patil", nextService: "2026-08-03", openWork: 0, runtimeHours: 6702 },
  { id: "AST-012", name: "Paint Booth PB-02", area: "Surface Treatment", health: "Attention", owner: "Uday Kulkarni", nextService: "2026-07-24", openWork: 2, runtimeHours: 11043 },
  { id: "AST-013", name: "Diesel Generator DG-01", area: "Utility Block", health: "Available", owner: "Divya Deshmukh", nextService: "2026-08-09", openWork: 0, runtimeHours: 8651 },
  { id: "AST-014", name: "Calibration Oven OV-03", area: "Metrology Lab", health: "Calibration hold", owner: "Chetan Kulkarni", nextService: "2026-07-21", openWork: 1, runtimeHours: 4930 },
  { id: "AST-015", name: "Forklift FL-06", area: "Project Stores", health: "Available", owner: "Gauri Patil", nextService: "2026-08-05", openWork: 0, runtimeHours: 14220 },
  { id: "AST-016", name: "Shot Blasting Machine SB-01", area: "Surface Treatment", health: "Down", owner: "Divya Patil", nextService: "2026-07-18", openWork: 2, runtimeHours: 19112 },
];

export const safetyRecords: SafetyRecord[] = [
  { id: "SAFE-001", title: "Damaged welding cable near aisle", kind: "Unsafe condition", area: "Welding Bay 3", owner: "Kavita Patil", state: "Blocked", due: "2026-07-18", severity: "High" },
  { id: "SAFE-002", title: "Grinding spark crossed temporary screen", kind: "Near miss", area: "Assembly Bay 2", owner: "Suresh Deshmukh", state: "In progress", due: "2026-07-19", severity: "High" },
  { id: "SAFE-003", title: "Confined space permit for LP2 heater", kind: "Permit", area: "Assembly Bay 2", owner: "Kavita Deshmukh", state: "Awaiting verification", due: "2026-07-18", severity: "High" },
  { id: "SAFE-004", title: "Night shift lifting toolbox talk", kind: "Toolbox talk", area: "Heavy Fabrication Bay", owner: "Kavita Patil", state: "Not started", due: "2026-07-18", severity: "Medium" },
  { id: "SAFE-005", title: "Oil spill beside VTL-02", kind: "Unsafe condition", area: "Machine Shop", owner: "Arjun Patil", state: "Awaiting verification", due: "2026-07-18", severity: "Medium" },
  { id: "SAFE-006", title: "Finger pinch during fixture alignment", kind: "Incident", area: "Integration Bay 2", owner: "Kavita Kulkarni", state: "In progress", due: "2026-07-21", severity: "Medium" },
  { id: "SAFE-007", title: "Forklift reverse alarm intermittent", kind: "Unsafe condition", area: "Project Stores", owner: "Gauri Patil", state: "Blocked", due: "2026-07-18", severity: "High" },
  { id: "SAFE-008", title: "Hot work permit for tube seam repair", kind: "Permit", area: "Welding Bay 4", owner: "Suresh Kulkarni", state: "Closed", due: "2026-07-18", severity: "High" },
  { id: "SAFE-009", title: "Loose scaffold toe board", kind: "Near miss", area: "Test Bay", owner: "Kavita Patil", state: "In progress", due: "2026-07-19", severity: "High" },
  { id: "SAFE-010", title: "Eye wash station flow below mark", kind: "Unsafe condition", area: "Chemical Store", owner: "Isha Patil", state: "In progress", due: "2026-07-20", severity: "Medium" },
  { id: "SAFE-011", title: "Compressed gas handling refresher", kind: "Toolbox talk", area: "Welding Bay 1", owner: "Kavita Kulkarni", state: "Closed", due: "2026-07-17", severity: "Low" },
  { id: "SAFE-012", title: "Unsecured plate on transfer trolley", kind: "Near miss", area: "Plate Yard", owner: "Aditi Patil", state: "Awaiting verification", due: "2026-07-19", severity: "High" },
  { id: "SAFE-013", title: "Paint booth respirator fit check", kind: "Permit", area: "Surface Treatment", owner: "Kavita Deshmukh", state: "Not started", due: "2026-07-20", severity: "Medium" },
  { id: "SAFE-014", title: "First aid case after sharp edge contact", kind: "Incident", area: "Machine Shop", owner: "Kavita Patil", state: "Awaiting verification", due: "2026-07-22", severity: "Low" },
  { id: "SAFE-015", title: "Emergency exit pallet obstruction", kind: "Unsafe condition", area: "Dispatch Bay", owner: "Jatin Patil", state: "Closed", due: "2026-07-18", severity: "High" },
];

export const kpis: KpiRecord[] = [
  { id: "KPI-001", name: "Zero accident", department: "Safety", owner: "Kavita Patil", target: "0", actual: "0", frequency: "Monthly", state: "On target", actionCount: 0, trend: "Flat" },
  { id: "KPI-002", name: "RT and UT repair", department: "Welding Engineering", owner: "Bhavna Patil", target: "≤2%", actual: "2.7%", frequency: "Monthly", state: "Off target", actionCount: 3, trend: "Worsening" },
  { id: "KPI-003", name: "On-time delivery", department: "Production", owner: "Aditi Patil", target: "≥98%", actual: "94.2%", frequency: "Monthly", state: "Off target", actionCount: 5, trend: "Worsening" },
  { id: "KPI-004", name: "Monthly sales target", department: "Finance & Accounts", owner: "Harish Patil", target: "₹8.5 crore", actual: "", frequency: "Monthly", state: "Missing update", actionCount: 1, trend: "Flat" },
  { id: "KPI-005", name: "Attrition rate", department: "HR & Administration", owner: "Isha Patil", target: "≤8%", actual: "", frequency: "Monthly", state: "Missing update", actionCount: 1, trend: "Flat" },
  { id: "KPI-006", name: "Welder qualification validity", department: "Welding Engineering", owner: "Bhavna Patil", target: "100%", actual: "98%", frequency: "Monthly", state: "At risk", actionCount: 2, trend: "Flat" },
  { id: "KPI-007", name: "Daily spot checks", department: "Welding Engineering", owner: "Bhavna Kulkarni", target: "30/month", actual: "22", frequency: "Monthly", state: "At risk", actionCount: 2, trend: "Worsening" },
  { id: "KPI-008", name: "Audit compliance", department: "Quality Assurance", owner: "Chetan Patil", target: "100%", actual: "", frequency: "Monthly", state: "Missing update", actionCount: 1, trend: "Flat" },
  { id: "KPI-009", name: "CAPA closure on time", department: "Quality Assurance", owner: "Chetan Patil", target: "≥95%", actual: "91%", frequency: "Monthly", state: "At risk", actionCount: 4, trend: "Improving" },
  { id: "KPI-010", name: "Calibration compliance", department: "Quality Control", owner: "Deepak Patil", target: "100%", actual: "96%", frequency: "Monthly", state: "At risk", actionCount: 2, trend: "Worsening" },
  { id: "KPI-011", name: "Traceability compliance", department: "Quality Assurance", owner: "Chetan Patil", target: "100%", actual: "100%", frequency: "Monthly", state: "On target", actionCount: 0, trend: "Flat" },
  { id: "KPI-012", name: "DPT and MPT acceptance", department: "Quality Control", owner: "Deepak Patil", target: "≥99%", actual: "99.3%", frequency: "Monthly", state: "On target", actionCount: 0, trend: "Improving" },
  { id: "KPI-013", name: "Critical process Cp/Cpk", department: "Production", owner: "Aditi Patil", target: "≥1.33", actual: "1.21", frequency: "Monthly", state: "Off target", actionCount: 3, trend: "Worsening" },
  { id: "KPI-014", name: "Internal audit completion", department: "Quality Assurance", owner: "Chetan Patil", target: "100%", actual: "", frequency: "Quarterly", state: "Missing update", actionCount: 1, trend: "Flat" },
  { id: "KPI-015", name: "Quality review meetings", department: "Quality Assurance", owner: "Chetan Patil", target: "4/month", actual: "2", frequency: "Monthly", state: "At risk", actionCount: 1, trend: "Flat" },
  { id: "KPI-016", name: "Customer complaints", department: "Quality Assurance", owner: "Chetan Patil", target: "0 major", actual: "1 major", frequency: "Monthly", state: "Off target", actionCount: 2, trend: "Worsening" },
  { id: "KPI-017", name: "Supplier rejection", department: "SCM", owner: "Gauri Patil", target: "≤1%", actual: "1.4%", frequency: "Monthly", state: "Off target", actionCount: 3, trend: "Worsening" },
  { id: "KPI-018", name: "Rework cost", department: "Quality Control", owner: "Deepak Patil", target: "≤0.5% of sales", actual: "0.42%", frequency: "Monthly", state: "On target", actionCount: 0, trend: "Improving" },
  { id: "KPI-019", name: "Scrap cost", department: "Production", owner: "Aditi Patil", target: "≤0.3% of sales", actual: "0.28%", frequency: "Monthly", state: "On target", actionCount: 0, trend: "Improving" },
  { id: "KPI-020", name: "RFQ to order conversion", department: "Business Development", owner: "Jatin Patil", target: "≥35%", actual: "31%", frequency: "Monthly", state: "At risk", actionCount: 2, trend: "Improving" },
  { id: "KPI-021", name: "On-time proposal submission", department: "Business Development", owner: "Jatin Patil", target: "100%", actual: "", frequency: "Monthly", state: "Missing update", actionCount: 1, trend: "Flat" },
  { id: "KPI-022", name: "Kick-off meeting completion", department: "Project Management", owner: "Farhan Patil", target: "100%", actual: "100%", frequency: "Per project", state: "On target", actionCount: 0, trend: "Flat" },
  { id: "KPI-023", name: "Approved project plan readiness", department: "Project Management", owner: "Farhan Patil", target: "100%", actual: "86%", frequency: "Monthly", state: "Off target", actionCount: 4, trend: "Worsening" },
  { id: "KPI-024", name: "Full kit readiness", department: "Project Management", owner: "Farhan Patil", target: "100%", actual: "92%", frequency: "Monthly", state: "At risk", actionCount: 5, trend: "Improving" },
  { id: "KPI-025", name: "Daily action closure", department: "Project Management", owner: "Farhan Patil", target: "≥95%", actual: "89%", frequency: "Daily", state: "Off target", actionCount: 8, trend: "Worsening" },
  { id: "KPI-026", name: "First pass yield", department: "Production", owner: "Aditi Patil", target: "≥98%", actual: "97.4%", frequency: "Monthly", state: "At risk", actionCount: 2, trend: "Improving" },
];

export const documents: DocumentRecord[] = [
  { id: "DOC-001", title: "GTAW procedure for DP28W", code: "WPS-17", revision: "R6", owner: "Bhavna Patil", area: "Welding Engineering", state: "Effective", effectiveDate: "2026-07-15", acknowledgements: "31/37" },
  { id: "DOC-002", title: "CIWS integrated shop trial plan", code: "ITP-CIWS-04", revision: "R2", owner: "Farhan Patil", area: "Project Management", state: "Review due", effectiveDate: "2026-06-21", acknowledgements: "12/16" },
  { id: "DOC-003", title: "Material traceability procedure", code: "QAP-09", revision: "R8", owner: "Chetan Patil", area: "Quality Assurance", state: "Effective", effectiveDate: "2026-06-01", acknowledgements: "78/83" },
  { id: "DOC-004", title: "Confined space entry procedure", code: "SOP-SAFE-12", revision: "R4", owner: "Kavita Patil", area: "Safety", state: "Effective", effectiveDate: "2026-05-18", acknowledgements: "83/83" },
  { id: "DOC-005", title: "Horizontal borer setup checklist", code: "WI-MS-22", revision: "R3", owner: "Arjun Patil", area: "Machine Shop", state: "Review due", effectiveDate: "2025-07-24", acknowledgements: "18/23" },
  { id: "DOC-006", title: "SAW station preventive maintenance", code: "PM-SAW-03", revision: "R5", owner: "Divya Patil", area: "Maintenance", state: "Effective", effectiveDate: "2026-04-09", acknowledgements: "14/16" },
  { id: "DOC-007", title: "Incoming plate inspection plan", code: "ITP-IQC-07", revision: "R1", owner: "Deepak Patil", area: "Quality Control", state: "Draft", effectiveDate: "2026-07-18", acknowledgements: "0/9" },
  { id: "DOC-008", title: "Supplier deviation approval workflow", code: "SOP-SCM-06", revision: "R2", owner: "Gauri Patil", area: "SCM", state: "Effective", effectiveDate: "2026-07-02", acknowledgements: "11/14" },
  { id: "DOC-009", title: "Night shift handover standard", code: "SOP-PROD-15", revision: "R1", owner: "Aditi Patil", area: "Production", state: "Draft", effectiveDate: "2026-07-18", acknowledgements: "0/42" },
  { id: "DOC-010", title: "Customer complaint response process", code: "SOP-QA-14", revision: "R7", owner: "Chetan Patil", area: "Quality Assurance", state: "Effective", effectiveDate: "2026-03-12", acknowledgements: "19/21" },
  { id: "DOC-011", title: "Project kick-off checklist", code: "PMG-CHK-01", revision: "R4", owner: "Farhan Patil", area: "Project Management", state: "Effective", effectiveDate: "2026-02-25", acknowledgements: "22/24" },
  { id: "DOC-012", title: "Employee induction handbook", code: "HR-HBK-02", revision: "R9", owner: "Isha Patil", area: "HR & Administration", state: "Review due", effectiveDate: "2025-08-01", acknowledgements: "76/83" },
  { id: "DOC-013", title: "Legacy RT acceptance procedure", code: "NDT-RT-03", revision: "R2", owner: "Deepak Patil", area: "NDT", state: "Superseded", effectiveDate: "2023-04-11", acknowledgements: "83/83" },
  { id: "DOC-014", title: "Export packing specification", code: "PKG-EX-05", revision: "R3", owner: "Jatin Patil", area: "Dispatch", state: "Effective", effectiveDate: "2026-06-28", acknowledgements: "10/12" },
  { id: "DOC-015", title: "Calibration recall and escalation", code: "SOP-MET-08", revision: "R5", owner: "Chetan Kulkarni", area: "Metrology Lab", state: "Review due", effectiveDate: "2025-07-20", acknowledgements: "8/11" },
];

export const suppliers: SupplierRecord[] = [
  { id: "SUP-001", name: "Ratnamani Metals", category: "Heat exchanger tubes", owner: "Gauri Patil", qualityScore: 94, deliveryScore: 82, openIssues: 2, nextCommitment: "Replacement tubes by 23 Jul", risk: "Medium" },
  { id: "SUP-002", name: "Key Tech Engineering", category: "Thread rolling", owner: "Gauri Kulkarni", qualityScore: 91, deliveryScore: 89, openIssues: 1, nextCommitment: "Trial report by 21 Jul", risk: "Low" },
  { id: "SUP-003", name: "Hardwin Engineers", category: "Precision machining", owner: "Rina Deshmukh", qualityScore: 86, deliveryScore: 78, openIssues: 3, nextCommitment: "Nozzle lot by 27 Jul", risk: "High" },
  { id: "SUP-004", name: "Martec Systems", category: "Control software", owner: "Farhan Patil", qualityScore: 96, deliveryScore: 87, openIssues: 2, nextCommitment: "Simulator build by 30 Jul", risk: "Medium" },
  { id: "SUP-005", name: "Ashok Leyland Defence", category: "Travelling platform", owner: "Gauri Patil", qualityScore: 93, deliveryScore: 92, openIssues: 1, nextCommitment: "Interface drawing by 22 Jul", risk: "Low" },
  { id: "SUP-006", name: "Apex Refractories", category: "Refractory lining", owner: "Sneha Deshmukh", qualityScore: 81, deliveryScore: 74, openIssues: 5, nextCommitment: "Anchor shortage recovery by 20 Jul", risk: "High" },
  { id: "SUP-007", name: "Precision NDT Services", category: "ECT and IRIS", owner: "Deepak Patil", qualityScore: 90, deliveryScore: 76, openIssues: 2, nextCommitment: "Agency mobilization by 24 Jul", risk: "High" },
  { id: "SUP-008", name: "Bharat Forgings", category: "Heavy forgings", owner: "Gauri Kulkarni", qualityScore: 88, deliveryScore: 84, openIssues: 3, nextCommitment: "Manway forging by 2 Aug", risk: "Medium" },
  { id: "SUP-009", name: "Tombo Industrial Gaskets", category: "Special gaskets", owner: "Gauri Patil", qualityScore: 97, deliveryScore: 95, openIssues: 0, nextCommitment: "Next lot by 29 Jul", risk: "Low" },
  { id: "SUP-010", name: "Orbit Industrial Gases", category: "Welding gases", owner: "Suresh Kulkarni", qualityScore: 92, deliveryScore: 97, openIssues: 0, nextCommitment: "Weekly refill on 22 Jul", risk: "Low" },
  { id: "SUP-011", name: "Nova Calibration Labs", category: "Calibration services", owner: "Chetan Patil", qualityScore: 89, deliveryScore: 80, openIssues: 2, nextCommitment: "UT set certificate by 19 Jul", risk: "Medium" },
  { id: "SUP-012", name: "Shield PPE Solutions", category: "Safety equipment", owner: "Kavita Patil", qualityScore: 95, deliveryScore: 93, openIssues: 1, nextCommitment: "Respirator kits by 25 Jul", risk: "Low" },
  { id: "SUP-013", name: "Metro Drives and Controls", category: "Machine electronics", owner: "Divya Patil", qualityScore: 84, deliveryScore: 71, openIssues: 4, nextCommitment: "SAW drive card by 20 Jul", risk: "High" },
  { id: "SUP-014", name: "Western Export Packers", category: "Export packing", owner: "Jatin Patil", qualityScore: 90, deliveryScore: 88, openIssues: 1, nextCommitment: "Packing crew by 21 Jul", risk: "Low" },
  { id: "SUP-015", name: "Deccan Alloy Steels", category: "Plates and bars", owner: "Gauri Patil", qualityScore: 87, deliveryScore: 79, openIssues: 3, nextCommitment: "Traceability dossier by 23 Jul", risk: "Medium" },
];

export const activity: ActivityRecord[] = [
  { id: "ACT-001", actor: "Rohit Kulkarni", action: "marked work as blocked", target: "WK-001 CIWS upper gun stand fit-up", time: "8 min ago" },
  { id: "ACT-002", actor: "Deepak Kulkarni", action: "submitted inspection evidence", target: "WK-002 Urea stripper root pass", time: "16 min ago" },
  { id: "ACT-003", actor: "Kavita Patil", action: "opened a high severity unsafe condition", target: "SAFE-001 damaged welding cable", time: "24 min ago" },
  { id: "ACT-004", actor: "Divya Kulkarni", action: "requested a drive card from stores", target: "AST-004 SAW Station SAW-03", time: "31 min ago" },
  { id: "ACT-005", actor: "Chetan Patil", action: "returned a finding for more evidence", target: "MNC-014 hold point bypass", time: "42 min ago" },
  { id: "ACT-006", actor: "Gauri Deshmukh", action: "reported a material shortage", target: "WK-014 full kit for section 4", time: "55 min ago" },
  { id: "ACT-007", actor: "Aditi Deshmukh", action: "submitted packing punch points", target: "WK-007 shutdown spares", time: "1 hr ago" },
  { id: "ACT-008", actor: "Farhan Patil", action: "escalated a milestone risk", target: "CIWS-26 integrated shop trial", time: "1 hr ago" },
  { id: "ACT-009", actor: "Harish Deshmukh", action: "placed equipment on calibration hold", target: "AST-007 UT Set UT-07", time: "2 hr ago" },
  { id: "ACT-010", actor: "Deepak Patil", action: "verified customer punch point closure", target: "WK-018 shutdown spares", time: "2 hr ago" },
  { id: "ACT-011", actor: "Isha Patil", action: "updated workforce availability", target: "Unit 2 day shift", time: "3 hr ago" },
  { id: "ACT-012", actor: "Chetan Kulkarni", action: "created a corrective action", target: "CAPA-003 gauge verification", time: "3 hr ago" },
  { id: "ACT-013", actor: "Bhavna Patil", action: "published a procedure revision", target: "DOC-001 WPS-17 R6", time: "4 hr ago" },
  { id: "ACT-014", actor: "Arjun Patil", action: "accepted a maintenance window", target: "AST-002 VTL-02", time: "4 hr ago" },
  { id: "ACT-015", actor: "Jatin Patil", action: "recorded supplier commitment", target: "SUP-014 Western Export Packers", time: "5 hr ago" },
  { id: "ACT-016", actor: "Gauri Patil", action: "raised supplier risk to high", target: "SUP-006 Apex Refractories", time: "5 hr ago" },
  { id: "ACT-017", actor: "Kavita Deshmukh", action: "submitted a confined space permit", target: "SAFE-003 LP2 heater entry", time: "6 hr ago" },
  { id: "ACT-018", actor: "Farhan Deshmukh", action: "closed the daily action review", target: "WK-011 CIWS-26", time: "11 hr ago" },
  { id: "ACT-019", actor: "Chetan Patil", action: "flagged a missing KPI update", target: "KPI-008 audit compliance", time: "Yesterday" },
  { id: "ACT-020", actor: "Ganesh Badgujar", action: "approved the Unit 1 shift plan", target: "18 Jul day shift", time: "Yesterday" },
];

const linkedEmployeeIds = new Set(Object.values(projectEmployeeAssignments).flat());
const auditFindingKinds = new Set<QualityRecord["kind"]>([
  "Major NC",
  "Minor NC",
  "Observation",
]);

export const workforceSummary = {
  required: 92,
  available: employees.length,
  gap: 92 - employees.length,
  unit1: employees.filter((employee) => employee.unit === "Unit 1").length,
  unit2: employees.filter((employee) => employee.unit === "Unit 2").length,
  present: employees.filter((employee) => employee.status === "Present").length,
  unavailable: employees.filter(
    (employee) => employee.status === "Absent" || employee.status === "On leave",
  ).length,
} as const;

export const operationalSummary = {
  openWork: workItems.filter((item) => item.state !== "Closed").length,
  blockedWork: workItems.filter((item) => item.state === "Blocked").length,
  highRiskProjects: projects.filter((project) => project.risk === "High").length,
  auditFindings: qualityRecords.filter((record) => auditFindingKinds.has(record.kind)).length,
  majorNonconformities: qualityRecords.filter((record) => record.kind === "Major NC").length,
  assetsDown: assets.filter((asset) => asset.health === "Down").length,
  openSafetyItems: safetyRecords.filter((record) => record.state !== "Closed").length,
  missingKpiUpdates: kpis.filter((kpi) => kpi.state === "Missing update").length,
  projectLinkedEmployees: linkedEmployeeIds.size,
  staffedProjectCodes: Object.keys(projectEmployeeAssignments).length,
} as const;

export const seedWorkItems = workItems;
export const seedProjects = projects;
export const seedQualityRecords = qualityRecords;
export const seedAssets = assets;
export const seedSafetyRecords = safetyRecords;
export const seedEmployees = employees;
export const seedKpis = kpis;
export const seedDocuments = documents;
export const seedSuppliers = suppliers;
export const seedActivity = activity;
